console_title_template = '{{ .UserName }}@{{ .HostName }}'
version = 3
final_space = true

[palette]
  black = '#262B44'
  darkgray = '#505050'
  err = '#D81E5B'
  err_sec = '#f6993c'
  main = '#9342ae'
  sec = '#4ad94a'
  white = '#E0DEF4'

[secondary_prompt]
  template = '  ❯ '
  foreground = 'p:sec'
  background = 'transparent'

[transient_prompt]
  template = ' ❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}p:err_sec{{end}}', '{{if eq .Code 0}}p:sec{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Icon }}  '
    foreground = 'p:white'
    type = 'os'
    style = 'diamond'
    background_templates = ['{{if gt .Code 0}}p:err{{end}}', '{{if eq .Code 0}}p:main{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '{{if .Venv }} ({{ .Venv }}) {{ end }}'
    foreground = 'p:white'
    powerline_symbol = ''
    background = 'p:darkgray'
    type = 'python'
    style = 'powerline'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'environment'
      fetch_virtual_env = true
      home_enabled = true

  [[blocks.segments]]
    template = '  {{ path .Path .Location }} '
    foreground = 'p:black'
    powerline_symbol = ''
    type = 'path'
    style = 'powerline'
    background_templates = ['{{if gt .Code 0}}p:err_sec{{end}}', '{{if eq .Code 0}}p:sec{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'folder'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'p:white'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

  [[blocks.segments]]
    template = '  {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} '
    foreground = 'p:white'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      branch_max_length = 25
      cache_duration = 'none'
      fetch_status = true
